### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by DK013** [tanchunsiong/MSDK_RawDataDemos#1]
![image](https://github.com/tanchunsiong/MSDK_RawDataDemos/assets/22991490/2c07a1a5-0098-40f4-908f-69358cc7333e)
I've been struggling with zoom for past 4 days without rest. Don't have the energy to speak further. Hope you can understand. Plaese see these errors

**Comment by tanchunsiong** [comment]
this error might require you to modify meeting_participants_ctrl_interface.h

Could you check if these is missing headers?

#ifndef _MEETING_ParticipantsCtrl_INTERFACE_H_
#define _MEETING_ParticipantsCtrl_INTERFACE_H_
#include "zoom_sdk_def.h"
#include "meeting_service_components/meeting_recording_interface.h"
#include "meeting_service_components/meeting_audio_interface.h"

BEGIN_ZOOM_SDK_NAMESPACE

**Comment by tanchunsiong** [comment]
I'm trying with the latest SDK v5.15.1.17995. 
Here are the errors encountered, and the steps to resolved are documented in readme.md

I'm posting them here for easy reference too.

<img width="331" alt="image" src="https://github.com/tanchunsiong/MSDK_RawDataDemos/assets/2926710/6839eb10-bad4-4b4c-a1d4-49611e35425e">

You might encounter these errors

Error	C3646	'GetAudioJoinType': unknown override specifier	
Error (active)	E0020	identifier "AudioType" is undefined	SkeletonDemo

In your meeting_participants_ctrl_interface.h, ensure you are add an addition reference to #include "meeting_service_components/meeting_audio_interface.h"

Rebuild and Run, it should resolve both errors above
