### ISSUE TITLE
onMeetingStatusChanged: 1647

### ISSUE THREAD

**Issue by fantasyEthan** [tanchunsiong/MSDK_RawDataDemos#4]
Hi,

I am using your MSDK_Demo for Windows to create my app. But when I launch the MSDK_Demo C++ program, I get the following:
SDK Initialized.
CreateNetworkConnectionHelper created.
NetworkConnectionHandler registered. Detecting proxy. onProxyDetectComplete
AuthService created.
AuthServiceEventListener added. eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBLZXkiOiJpc1ZUWHZaQVNhZWhTZFZEalgzOHlRIiwic2RrS2V5IjoiaXNWVFh2WkFTYWVoU2RWRGpYMzh5USIsImlhdCI6MTcxOTQwOTYxMywiZXhwIjoxNzE5NDEzNTEzLCJ0b2tlbkV4cCI6MTcxOTQxMzUxMywibW4iOjk4OTg1MzMzMTMsInJvbGUiOjF9.rUkVaWXK03VbK4YUFe1EFZMW7lMYwGT2U8Ghl2QfTbI Auth call started, auth in progress.
Auth succeeded: JWT.
onLoginReturnWithReason: 0
MeetingService created.
Joining Meeting…
onMeetingStatusChanged: 1, iResult: 0 
onMeetingStatusChanged: 6, iResult: 63 
onMeetingStatusChanged: 4, iResult: 0 
onMeetingStatusChanged: 7, iResult: 0

I’ve generated the JWT using my own key and secret. Also, I use my personal room number in accordance with my development account. I’ve checked the error code, but it seems unreasonable to me because the meeting room is open and the passcode is correct.

PS: I can successfully run the official demo in the sdk provided.

Can anyone help me out? It’d be appreciated.

BRs

**Comment by tanchunsiong** [comment]
Error 63 means you are trying to join an external meeting without publishing your app. Support will be done via devforum.zoom.us

Will be closing this ticket as it is not a code level bug

**Comment by tanchunsiong** [comment]
@fantasyEthan tag me on the dev forum if you still have issues, I'll troubleshoot it
